Repository let-eat-go/backend, pull requests merged in 2024-01, with the labels that each got.

#4 [#2] 로컬 회원가입, 로그인
  .docker/docker-compose.yml
  .gitignore
  build.gradle
  src/main/java/com/leteatgo/domain/auth/controller/AuthController.java
  src/main/java/com/leteatgo/domain/auth/dto/request/EmailCheckRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SignInRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SmsSendRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SmsVerifyRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/response/SignUpResponse.java
  src/main/java/com/leteatgo/domain/auth/entity/RedisSms.java
  src/main/java/com/leteatgo/domain/auth/entity/RedisToken.java
  src/main/java/com/leteatgo/domain/auth/exception/AuthException.java
  src/main/java/com/leteatgo/domain/auth/exception/TokenException.java
  src/main/java/com/leteatgo/domain/auth/repository/RedisSmsRepository.java
  src/main/java/com/leteatgo/domain/auth/repository/RedisTokenRepository.java
  src/main/java/com/leteatgo/domain/auth/service/AuthService.java
  src/main/java/com/leteatgo/domain/auth/service/CoolSmsSender.java
  src/main/java/com/leteatgo/domain/auth/service/SmsSender.java
  src/main/java/com/leteatgo/domain/auth/service/TokenService.java
  src/main/java/com/leteatgo/domain/member/entity/Member.java
  src/main/java/com/leteatgo/domain/member/repository/MemberRepository.java
  src/main/java/com/leteatgo/domain/member/type/MemberRole.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/controller/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/request/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/response/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/service/.gitkeep
  src/main/java/com/leteatgo/global/config/CoolSmsConfig.java
  src/main/java/com/leteatgo/global/config/SecurityConfig.java
  src/main/java/com/leteatgo/global/exception/ErrorCode.java
  src/main/java/com/leteatgo/global/exception/GlobalExceptionHandler.java
  src/main/java/com/leteatgo/global/security/CustomUserDetailService.java
  src/main/java/com/leteatgo/global/security/CustomUserDetails.java
  src/main/java/com/leteatgo/global/security/annotation/RoleAdmin.java
  src/main/java/com/leteatgo/global/security/annotation/RoleUser.java
  src/main/java/com/leteatgo/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/leteatgo/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/leteatgo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/leteatgo/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/leteatgo/global/util/CookieUtil.java
  src/main/java/com/leteatgo/global/util/DtoValidator.java
  src/main/resources/application-common.yml
  src/main/resources/application-test.yml
  src/main/resources/properties/env.properties.example
  src/test/java/com/leteatgo/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/leteatgo/domain/auth/service/AuthServiceTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantControllerTest.java
Labels: 🚀 Feat, ✅ Test

#9 [#5] 구글 로그인 구현
  build.gradle
  src/main/java/com/leteatgo/domain/auth/controller/AuthController.java
  src/main/java/com/leteatgo/domain/auth/dto/response/SignInResponse.java
  src/main/java/com/leteatgo/domain/auth/service/AuthService.java
  src/main/java/com/leteatgo/domain/member/entity/Member.java
  src/main/java/com/leteatgo/global/config/SecurityConfig.java
  src/main/java/com/leteatgo/global/exception/ErrorCode.java
  src/main/java/com/leteatgo/global/security/CustomOAuth2UserDetails.java
  src/main/java/com/leteatgo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/leteatgo/global/security/oauth/dto/OAuth2UserInfo.java
  src/main/java/com/leteatgo/global/security/oauth/handler/CustomOAuth2FailureHandler.java
  src/main/java/com/leteatgo/global/security/oauth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/leteatgo/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/leteatgo/global/security/oauth/service/OAuth2Provider.java
  src/main/java/com/leteatgo/global/util/CookieUtil.java
  src/main/resources/application-common.yml
  src/test/java/com/leteatgo/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/leteatgo/domain/auth/service/AuthServiceTest.java
Labels: 🚀 Feat

#10 [#7] 회원들이 방문한 맛집 조회
  .gitignore
  src/main/java/com/leteatgo/domain/tastyrestaurant/controller/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantController.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/request/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/request/SearchRestaurantsRequest.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/response/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/response/SearchRestaurantsResponse.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/response/VisitedRestaurantResponse.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/entity/TastyRestaurant.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/CustomTastyRestaurantRepository.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/TastyRestaurantRepository.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/impl/CustomTastyRestaurantRepositoryImpl.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/service/.gitkeep
  src/main/java/com/leteatgo/domain/tastyrestaurant/service/TastyRestaurantService.java
  src/main/java/com/leteatgo/global/config/QuerydslConfig.java
  src/main/java/com/leteatgo/global/config/SecurityConfig.java
  src/main/java/com/leteatgo/global/exception/ErrorCode.java
  src/main/java/com/leteatgo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/leteatgo/global/type/RestaurantCategory.java
  src/main/java/com/leteatgo/global/util/DtoValidator.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantControllerTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/repository/impl/CustomTastyRestaurantRepositoryImplTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/service/TastyRestaurantServiceTest.java
  src/test/java/com/leteatgo/http/auth.http
  src/test/java/com/leteatgo/http/tastyRestaurant.http
Labels: 🚀 Feat, ✅ Test

#13 2주차 멘토링 피드백 반영
  src/main/java/com/leteatgo/domain/auth/dto/request/EmailCheckRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SignInRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SmsSendRequest.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SmsVerifyRequest.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantController.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/request/SearchRestaurantsRequest.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/request/VisitedRestaurantRequest.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/dto/response/VisitedRestaurantResponse.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/entity/TastyRestaurant.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/CustomTastyRestaurantRepository.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/TastyRestaurantRepository.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/repository/impl/CustomTastyRestaurantRepositoryImpl.java
  src/main/java/com/leteatgo/domain/tastyrestaurant/service/TastyRestaurantService.java
  src/main/java/com/leteatgo/global/constants/DtoValid.java
  src/main/java/com/leteatgo/global/external/searchplace/client/kakao/client/KakaoApiClient.java
  src/main/java/com/leteatgo/global/external/searchplace/client/kakao/config/KakaoApiConfig.java
  src/main/java/com/leteatgo/global/type/RestaurantCategory.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantControllerTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/repository/impl/CustomTastyRestaurantRepositoryImplTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/service/TastyRestaurantServiceTest.java
Labels: 🐛 Bug, ♻️ Refactor

#15 [#12] 회원가입 로직 수정
  src/main/java/com/leteatgo/domain/auth/controller/AuthController.java
  src/main/java/com/leteatgo/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/leteatgo/domain/auth/service/AuthService.java
  src/main/java/com/leteatgo/domain/auth/service/CoolSmsSender.java
  src/main/java/com/leteatgo/global/security/jwt/JwtAuthenticationFilter.java
  src/test/java/com/leteatgo/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/leteatgo/domain/auth/service/AuthServiceTest.java
Labels: ♻️ Refactor

#18 [#11] dev브랜치 CI/CD 구축
  .docker/api/Dockerfile-api
  .docker/docker-compose-dev.yml
  .docker/docker-compose.yml
  .docker/nginx/Dockerfile-nginx
  .docker/nginx/nginx-dev.conf
  .github/workflows/deploy-dev.yml
  build.gradle
  src/main/java/com/leteatgo/domain/auth/service/AuthService.java
  src/main/java/com/leteatgo/global/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/static/docs/leteatgo-api.yaml
Labels: 🛠 Setting, 💣 CI/CD

#19 [#14] 채팅 설정 및 발행
  build.gradle
  src/main/java/com/leteatgo/domain/chat/controller/.gitkeep
  src/main/java/com/leteatgo/domain/chat/controller/ChatMessageController.java
  src/main/java/com/leteatgo/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/leteatgo/domain/chat/dto/request/.gitkeep
  src/main/java/com/leteatgo/domain/chat/dto/response/.gitkeep
  src/main/java/com/leteatgo/domain/chat/entity/ChatMessage.java
  src/main/java/com/leteatgo/domain/chat/entity/ChatRoom.java
  src/main/java/com/leteatgo/domain/chat/event/ChatRoomEventHandler.java
  src/main/java/com/leteatgo/domain/chat/event/ChatRoomEventPublisher.java
  src/main/java/com/leteatgo/domain/chat/event/dto/CloseChatRoomEvent.java
  src/main/java/com/leteatgo/domain/chat/event/dto/CreateChatRoomEvent.java
  src/main/java/com/leteatgo/domain/chat/repository/.gitkeep
  src/main/java/com/leteatgo/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/leteatgo/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/leteatgo/domain/chat/service/.gitkeep
  src/main/java/com/leteatgo/domain/chat/service/ChatMessageService.java
  src/main/java/com/leteatgo/domain/chat/service/ChatRoomService.java
  src/main/java/com/leteatgo/domain/chat/type/RoomStatus.java
  src/main/java/com/leteatgo/domain/meeting/repository/.gitkeep
  src/main/java/com/leteatgo/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/leteatgo/global/config/AsyncConfig.java
  src/main/java/com/leteatgo/global/config/SecurityConfig.java
  src/main/java/com/leteatgo/global/config/WebSocketConfig.java
  src/main/java/com/leteatgo/global/exception/ErrorCode.java
  src/main/java/com/leteatgo/global/security/CustomUserDetailService.java
  src/main/java/com/leteatgo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/leteatgo/global/socket/handler/SocketErrorHandler.java
  src/main/java/com/leteatgo/global/socket/interceptor/SocketInterceptor.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/controller/TastyRestaurantControllerTest.java
  src/test/java/com/leteatgo/domain/tastyrestaurant/service/TastyRestaurantServiceTest.java
Labels: 🚀 Feat, ✅ Test
